// Code generated by 'yaegi extract github.com/coder/websocket'. DO NOT EDIT.

package websocket

import (
	"github.com/coder/websocket"
	"reflect"
)

func init() {
	Symbols["github.com/coder/websocket/websocket"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Accept":                        reflect.ValueOf(websocket.Accept),
		"CloseStatus":                   reflect.ValueOf(websocket.CloseStatus),
		"CompressionContextTakeover":    reflect.ValueOf(websocket.CompressionContextTakeover),
		"CompressionDisabled":           reflect.ValueOf(websocket.CompressionDisabled),
		"CompressionNoContextTakeover":  reflect.ValueOf(websocket.CompressionNoContextTakeover),
		"Dial":                          reflect.ValueOf(websocket.Dial),
		"ErrMessageTooBig":              reflect.ValueOf(&websocket.ErrMessageTooBig).Elem(),
		"MessageBinary":                 reflect.ValueOf(websocket.MessageBinary),
		"MessageText":                   reflect.ValueOf(websocket.MessageText),
		"NetConn":                       reflect.ValueOf(websocket.NetConn),
		"StatusAbnormalClosure":         reflect.ValueOf(websocket.StatusAbnormalClosure),
		"StatusBadGateway":              reflect.ValueOf(websocket.StatusBadGateway),
		"StatusGoingAway":               reflect.ValueOf(websocket.StatusGoingAway),
		"StatusInternalError":           reflect.ValueOf(websocket.StatusInternalError),
		"StatusInvalidFramePayloadData": reflect.ValueOf(websocket.StatusInvalidFramePayloadData),
		"StatusMandatoryExtension":      reflect.ValueOf(websocket.StatusMandatoryExtension),
		"StatusMessageTooBig":           reflect.ValueOf(websocket.StatusMessageTooBig),
		"StatusNoStatusRcvd":            reflect.ValueOf(websocket.StatusNoStatusRcvd),
		"StatusNormalClosure":           reflect.ValueOf(websocket.StatusNormalClosure),
		"StatusPolicyViolation":         reflect.ValueOf(websocket.StatusPolicyViolation),
		"StatusProtocolError":           reflect.ValueOf(websocket.StatusProtocolError),
		"StatusServiceRestart":          reflect.ValueOf(websocket.StatusServiceRestart),
		"StatusTLSHandshake":            reflect.ValueOf(websocket.StatusTLSHandshake),
		"StatusTryAgainLater":           reflect.ValueOf(websocket.StatusTryAgainLater),
		"StatusUnsupportedData":         reflect.ValueOf(websocket.StatusUnsupportedData),

		// type definitions
		"AcceptOptions":   reflect.ValueOf((*websocket.AcceptOptions)(nil)),
		"CloseError":      reflect.ValueOf((*websocket.CloseError)(nil)),
		"CompressionMode": reflect.ValueOf((*websocket.CompressionMode)(nil)),
		"Conn":            reflect.ValueOf((*websocket.Conn)(nil)),
		"DialOptions":     reflect.ValueOf((*websocket.DialOptions)(nil)),
		"MessageType":     reflect.ValueOf((*websocket.MessageType)(nil)),
		"StatusCode":      reflect.ValueOf((*websocket.StatusCode)(nil)),
	}
}
