// Code generated by 'yaegi extract github.com/PaesslerAG/gval'. DO NOT EDIT.

package jsonpath

import (
	"context"
	"github.com/PaesslerAG/gval"
	"reflect"
)

func init() {
	Symbols["github.com/PaesslerAG/gval/gval"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Arithmetic":           reflect.ValueOf(gval.Arithmetic),
		"Base":                 reflect.ValueOf(gval.Base),
		"Bitmask":              reflect.ValueOf(gval.Bitmask),
		"Constant":             reflect.ValueOf(gval.Constant),
		"DecimalArithmetic":    reflect.ValueOf(gval.DecimalArithmetic),
		"DefaultExtension":     reflect.ValueOf(gval.DefaultExtension),
		"Evaluate":             reflect.ValueOf(gval.Evaluate),
		"EvaluateWithContext":  reflect.ValueOf(gval.EvaluateWithContext),
		"Full":                 reflect.ValueOf(gval.Full),
		"Function":             reflect.ValueOf(gval.Function),
		"Ident":                reflect.ValueOf(gval.Ident),
		"InfixBoolOperator":    reflect.ValueOf(gval.InfixBoolOperator),
		"InfixDecimalOperator": reflect.ValueOf(gval.InfixDecimalOperator),
		"InfixEvalOperator":    reflect.ValueOf(gval.InfixEvalOperator),
		"InfixNumberOperator":  reflect.ValueOf(gval.InfixNumberOperator),
		"InfixOperator":        reflect.ValueOf(gval.InfixOperator),
		"InfixShortCircuit":    reflect.ValueOf(gval.InfixShortCircuit),
		"InfixTextOperator":    reflect.ValueOf(gval.InfixTextOperator),
		"Init":                 reflect.ValueOf(gval.Init),
		"JSON":                 reflect.ValueOf(gval.JSON),
		"NewLanguage":          reflect.ValueOf(gval.NewLanguage),
		"Parentheses":          reflect.ValueOf(gval.Parentheses),
		"PostfixOperator":      reflect.ValueOf(gval.PostfixOperator),
		"Precedence":           reflect.ValueOf(gval.Precedence),
		"PrefixExtension":      reflect.ValueOf(gval.PrefixExtension),
		"PrefixMetaPrefix":     reflect.ValueOf(gval.PrefixMetaPrefix),
		"PrefixOperator":       reflect.ValueOf(gval.PrefixOperator),
		"PropositionalLogic":   reflect.ValueOf(gval.PropositionalLogic),
		"TernaryOperator":      reflect.ValueOf(gval.TernaryOperator),
		"Text":                 reflect.ValueOf(gval.Text),
		"VariableSelector":     reflect.ValueOf(gval.VariableSelector),

		// type definitions
		"Evaluable":  reflect.ValueOf((*gval.Evaluable)(nil)),
		"Evaluables": reflect.ValueOf((*gval.Evaluables)(nil)),
		"Language":   reflect.ValueOf((*gval.Language)(nil)),
		"Parser":     reflect.ValueOf((*gval.Parser)(nil)),
		"Selector":   reflect.ValueOf((*gval.Selector)(nil)),

		// interface wrapper definitions
		"_Selector": reflect.ValueOf((*_github_com_PaesslerAG_gval_Selector)(nil)),
	}
}

// _github_com_PaesslerAG_gval_Selector is an interface wrapper for Selector type
type _github_com_PaesslerAG_gval_Selector struct {
	IValue      interface{}
	WSelectGVal func(c context.Context, key string) (interface{}, error)
}

func (W _github_com_PaesslerAG_gval_Selector) SelectGVal(c context.Context, key string) (interface{}, error) {
	return W.WSelectGVal(c, key)
}
