// SPDX-FileCopyrightText: 2023 Iván Szkiba
//
// SPDX-License-Identifier: MIT

// Code generated by 'yaegi extract github.com/PaesslerAG/jsonpath'. DO NOT EDIT.

package jsonpath

import (
	"github.com/PaesslerAG/jsonpath"
	"reflect"
)

func init() {
	Symbols["github.com/PaesslerAG/jsonpath/jsonpath"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Get":                  reflect.ValueOf(jsonpath.Get),
		"Language":             reflect.ValueOf(jsonpath.Language),
		"New":                  reflect.ValueOf(jsonpath.New),
		"PlaceholderExtension": reflect.ValueOf(jsonpath.PlaceholderExtension),
	}
}
