# SPDX-FileCopyrightText: 2023 Iván Szkiba
#
# SPDX-License-Identifier: MIT

name: Build
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - feature/*

jobs:
  build:
    name: Bundle xk6 extensions
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        id: build
        uses: szkiba/xk6bundler@v0
        with:
          with: github.com/szkiba/xk6-g0=/github/workspace
